name: Push new version to Internal

on:
  workflow_dispatch:
    inputs:
      aab_file:
        description: "–ò–º—è —Ñ–∞–π–ª–∞ .aab –¥–ª—è –∑–∞–ª–∏–≤–∫–∏ (–Ω–∞–ø—Ä–∏–º–µ—Ä: Final_Goal_Fever_1.aab)"
        required: true
        default: "Final_Goal_Fever_1.aab"
      release_tag:
        description: "–¢–µ–≥ —Ä–µ–ª–∏–∑–∞ (–Ω–∞–ø—Ä–∏–º–µ—Ä: 1.0.0)"
        required: true
        default: "1.0.0"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download AAB from GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p build_output
          echo "‚¨áÔ∏è –°–∫–∞—á–∏–≤–∞–µ–º ${{ github.event.inputs.aab_file }} –∏–∑ —Ä–µ–ª–∏–∑–∞ ${{ github.event.inputs.release_tag }}"
          gh release download ${{ github.event.inputs.release_tag }} \
            --pattern "${{ github.event.inputs.aab_file }}" \
            --dir build_output
          echo "üìÇ –§–∞–π–ª—ã –ø–æ—Å–ª–µ —Å–∫–∞—á–∏–≤–∞–Ω–∏—è:"
          ls -lh build_output
          mv "build_output/${{ github.event.inputs.aab_file }}" build_output/app.aab
          echo "üìÇ –§–∞–π–ª—ã –ø–æ—Å–ª–µ –ø–µ—Ä–µ–∏–º–µ–Ω–æ–≤–∞–Ω–∏—è:"
          ls -lh build_output

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          
      - name: Install Fastlane
        run: gem install fastlane

      - name: Run Fastlane uploading
        env:
          GOOGLE_PLAY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}
          AAB_FILE: ${{ github.event.inputs.aab_file }}
        run: |
          export GOOGLE_PLAY_JSON_KEY="$(echo "$GOOGLE_PLAY_JSON_KEY")"
          fastlane android upload_to_internal
        working-directory: .github/fastlane
